<a href="https://colab.research.google.com/github/devmurarijay13/pytorch-deep-learning/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.10.0+cpu


In [ ]:
if torch.cuda.is_available():
    print('GPU is available')
    print(torch.cuda.get_device_name(0))
else:
    print('GPU is not available')

GPU is not available


## Creating Tensors

In [ ]:
## using empty
a = torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
## using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
## using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
## using rand
torch.rand(2,3)

tensor([[0.1953, 0.0175, 0.9970],
        [0.6268, 0.2323, 0.2631]])

In [ ]:
## mannual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
## torch arange
## torch linspace
## torch eye
# torch full

## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[539106833,         0,         0],
        [       65, 487562992, 538990704]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
## rand_like generate float by default
torch.rand_like(x,dtype=torch.float16)

tensor([[0.9609, 0.9424, 0.1709],
        [0.9629, 0.9229, 0.0259]], dtype=torch.float16)

## Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
## assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
## using to() -- change dtype of ALREADY created tensor
x.to(torch.float16)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

## Mathemetical Operations

#### Scalar Operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
### add
x + 2

## subs
x - 3

## multi
x * 100

## division
x / 5

## int division
(x*100)//2

## mod
(x*100)//2 % 2

### power
x ** 2

tensor([[1., 1.],
        [0., 1.]])

#### Element wise operation

In [ ]:
a = torch.rand(3,3)
b = torch.rand(3,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238],
        [0.5557, 0.9770, 0.4440]])
tensor([[0.9478, 0.7445, 0.4892],
        [0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [ ]:
a + b

#sub
a-b

#multi
a*b

#div
a/b

tensor([[1.0517, 1.0162, 0.4577],
        [1.2465, 0.2548, 1.5612],
        [2.2483, 1.2354, 1.0485]])

In [ ]:
c = torch.tensor([1,-2,-3,4])

In [ ]:
## abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
## neg
torch.neg(c)

tensor([-1,  2,  3, -4])

In [ ]:
d = torch.tensor([7.9,12.1,13.10,55.01])
torch.round(d)

tensor([ 8., 12., 13., 55.])

In [ ]:
## clamp -- set all the values within range
torch.clamp(d,min=10,max=13)

tensor([10.0000, 12.1000, 13.0000, 13.0000])

#### Reduction Operations

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [ ]:
torch.sum(e)

tensor(42.)

In [ ]:
torch.sum(e,dim=0) ## sum of column

tensor([14., 16., 12.])

In [ ]:
torch.sum(e,dim=1) ## sum of row

tensor([17., 25.])

In [ ]:
## mean
torch.mean(e)

## row wise
torch.mean(e,dim=1)

tensor([5.6667, 8.3333])

In [ ]:
## median
torch.median(e)

tensor(7.)

In [ ]:
torch.max(e)

tensor(9.)

In [ ]:
torch.min(e)

tensor(5.)

In [ ]:
 torch.prod(e)

tensor(99225.)

In [ ]:
torch.std(e)

tensor(1.7889)

In [ ]:
torch.var(e)

tensor(3.2000)

In [ ]:
## return the position of biggest element
torch.argmax(e)

tensor(3)

In [ ]:
## return the position of biggest element
torch.argmin(e)

tensor(0)

#### MATRIX OPERATIONS

In [ ]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [ ]:
torch.matmul(f,g)

tensor([[137, 117],
        [139, 130]])

In [ ]:
## dot product
vec1 = torch.tensor([1,2,3])
vec2 = torch.tensor([4,5,6])

torch.dot(vec1,vec2)

tensor(32)

In [ ]:
## transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

## Special Functions

In [ ]:
t = torch.randint(size=(5,5),low=1,high=10,dtype=torch.float32)
t

tensor([[6., 7., 4., 7., 7.],
        [7., 9., 9., 1., 9.],
        [7., 6., 5., 2., 1.],
        [8., 6., 7., 2., 1.],
        [7., 4., 1., 2., 8.]])

In [ ]:
torch.log(t)

tensor([[1.7918, 1.9459, 1.3863, 1.9459, 1.9459],
        [1.9459, 2.1972, 2.1972, 0.0000, 2.1972],
        [1.9459, 1.7918, 1.6094, 0.6931, 0.0000],
        [2.0794, 1.7918, 1.9459, 0.6931, 0.0000],
        [1.9459, 1.3863, 0.0000, 0.6931, 2.0794]])

In [ ]:
torch.exp(t)

tensor([[4.0343e+02, 1.0966e+03, 5.4598e+01, 1.0966e+03, 1.0966e+03],
        [1.0966e+03, 8.1031e+03, 8.1031e+03, 2.7183e+00, 8.1031e+03],
        [1.0966e+03, 4.0343e+02, 1.4841e+02, 7.3891e+00, 2.7183e+00],
        [2.9810e+03, 4.0343e+02, 1.0966e+03, 7.3891e+00, 2.7183e+00],
        [1.0966e+03, 5.4598e+01, 2.7183e+00, 7.3891e+00, 2.9810e+03]])

In [ ]:
torch.softmax(t,dim=0)

tensor([[6.0445e-02, 1.0900e-01, 5.8049e-03, 9.7781e-01, 8.9990e-02],
        [1.6431e-01, 8.0538e-01, 8.6153e-01, 2.4238e-03, 6.6494e-01],
        [1.6431e-01, 4.0098e-02, 1.5779e-02, 6.5884e-03, 2.2306e-04],
        [4.4663e-01, 4.0098e-02, 1.1660e-01, 6.5884e-03, 2.2306e-04],
        [1.6431e-01, 5.4266e-03, 2.8901e-04, 6.5884e-03, 2.4462e-01]])

In [ ]:
torch.relu(t)

tensor([[6., 7., 4., 7., 7.],
        [7., 9., 9., 1., 9.],
        [7., 6., 5., 2., 1.],
        [8., 6., 7., 2., 1.],
        [7., 4., 1., 2., 8.]])

## Inplace Operations

In [ ]:
###we use functionname with _ at end to perform inplace operations

## Copying a Tensor

In [ ]:
a = torch.randint(size=(3,3),high=20,low=10,dtype=torch.float32)

In [ ]:
b = a

In [ ]:
a[0][0] = 444

In [ ]:
a

tensor([[444.,  17.,  10.],
        [ 12.,  14.,  14.],
        [ 16.,  12.,  11.]])

In [ ]:
b

tensor([[444.,  17.,  10.],
        [ 12.,  14.,  14.],
        [ 16.,  12.,  11.]])

In [ ]:
id(a) == id(b)

True

In [ ]:
b = a.clone()

In [ ]:
a[0][1] = 10000

In [ ]:
a

tensor([[  444., 10000.,    10.],
        [   12.,    14.,    14.],
        [   16.,    12.,    11.]])

In [ ]:
b

tensor([[444.,  17.,  10.],
        [ 12.,  14.,  14.],
        [ 16.,  12.,  11.]])

In [ ]:
id(a) == id(b)

False

## Tensor Operations on GPU

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# create new tensor on GPU
torch.rand(2,3,device=device)

tensor([[0.9815, 0.5687, 0.2239],
        [0.1282, 0.8414, 0.5714]], device='cuda:0')

In [ ]:
## moving existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.5198, 0.6352, 0.9253],
        [0.0591, 0.0412, 0.4047]])

In [ ]:
b = a.to(device)

In [ ]:
b * 100

tensor([[51.9814, 63.5198, 92.5322],
        [ 5.9058,  4.1186, 40.4698]], device='cuda:0')

## Reshaping Tensor

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
## flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.1340, 0.2462, 0.0128, 0.2883],
         [0.7755, 0.7104, 0.4127, 0.3537],
         [0.9294, 0.8837, 0.8807, 0.3430]],

        [[0.5526, 0.4744, 0.7172, 0.3572],
         [0.5325, 0.0471, 0.8823, 0.5878],
         [0.8439, 0.7303, 0.3497, 0.9763]]])

In [ ]:
### permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [ ]:
### unsqueeze ---- it will add new dim on give position
c = torch.rand(226,226,3)


In [ ]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [ ]:
### squeeze
x = torch.rand(1,20)

In [ ]:
x.squeeze().shape

torch.Size([20])